services:
  samba:
    image: dperson/samba
    container_name: samba-server
    restart: unless-stopped
    environment:
      - USERID=1000
      - GROUPID=1000
      - TZ=America/Sao_Paulo
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /mnt/storage:/mount/storage
    command: >
      -s "storage;/mount/storage;yes;no;no;all;lolli;lollilolli"
      -u "lolli;lollilolli"
