services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db:/var/lib/mysql
  
  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.3-php8.1-fpm
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=exampledb
    volumes:
      - wordpress:/var/www/html
  
  nginx:
    depends_on:
      - wordpress
    image: nginx:1.25.4
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d

volumes:
  wordpress:
  db: