version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=exampledb
    volumes:
      - wordpress:/var/www/html

  nginx:
    depends_on:
      - wordpress
    image: nginx
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/templates/default.conf.template

volumes:
  wordpress:
  db: