services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=exampledb
    volumes:
      - db:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    # user: 33:33
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=example
      - WORDPRESS_DB_NAME=exampledb
    volumes:
      - wordpress:/var/www/html

  nginx:
    depends_on:
      - wordpress
    image: nginx
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/templates/default.conf.template

volumes:
  wordpress:
  db: