services:
  postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=teste
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgresql_data:
    external: true