services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    volumes:
      - listmonk_postgresql_data:/var/lib/postgresql/data

  app:
    image: listmonk/listmonk:v3.0.0
    ports:
      - 9000:9000
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./config.toml:/listmonk/config.toml

volumes:
  listmonk_postgresql_data:
    external: true