# implementação sem banco postgresql

services:
  n8n:
    # image: docker.n8n.io/n8nio/n8n
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    ports:
      - 5678:5678

volumes:
  n8n_data:
    external: true