services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306 
    environment:
      - MYSQL_ROOT_PASSWORD=teste
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=teste
      - MYSQL_DATABASE=teste
    volumes:
      - mysql_data:/var/lib/mysql

  glpi:
    image: elestio/glpi:latest
    ports:
      - 80:80
    volumes:
      - glpi:/var/www/html/glpi
    environment:
      - TIMEZONE=America/Sao_Paulo
      - ADMIN_EMAIL=admin@email.com
      - ADMIN_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=teste
      - MYSQL_DATABASE=teste
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=teste

volumes:
  mysql_data:
  glpi: