services:
  nextcloud_mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
    volumes:
      - nextcloud_mysql:/var/lib/mysql

  nextcloud_redis:
    image: redis
    volumes:
      - nextcloud_redis_data:/data
    command: redis-server --requirepass nextcloud

  nextcloud:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=nextcloud_mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - OVERWRITEPROTOCOL=http
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_custom_app:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
      - nextcloud_themes:/var/www/html/themes

  nginx:
    image: nginx
    environment:
      - FPM_HOST=nextcloud
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - nextcloud:/var/www/html
      - nextcloud_custom_app:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
      - nextcloud_themes:/var/www/html/themes
    ports:
      - 80:80

volumes:
  nextcloud_mysql:
    external: true
  nextcloud_redis_data:
    external: true
  nextcloud:
    external: true
  nextcloud_custom_app:
    external: true
  nextcloud_config:
    external: true
  nextcloud_data:
    external: true
  nextcloud_themes:
    external: true
