FROM nextcloud:28.0.2-fpm

# configuração para customização
# copia as imagens para a configuração visual do Nextcloud
# COPY images/logo.png /
# COPY images/background.jpg /

# instala dependencias para a geração dos favicons automaticamente
# RUN set -ex;
# RUN apt-get update;
# RUN apt-get install -y --no-install-recommends libmagickcore-6.q16-3-extra;
# RUN rm -rf /var/lib/apt/lists/*;