services:
  rabbitmq:
    image: rabbitmq:3.9.29-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER_FILE: rabbitmq
      RABBITMQ_DEFAULT_PASS_FILE: rabbitmq
          