services:
  wordpress-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=exampledb
    volumes:
      - wordpress_db:/var/lib/mysql

  wordpress:
    depends_on:
      - wordpress-db
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=example
      - WORDPRESS_DB_NAME=exampledb
    volumes:
      - wordpress:/var/www/html
    ports:
      - 80:80

volumes:
  wordpress_db:
    external: true
  wordpress:
    external: true