services:
  browserless:
    image: browserless/chrome:latest
    ports:
      - "3000:3000"
    environment:
      - TOKEN=meu-token
      - MAX_CONCURRENT_SESSIONS=5
      - CONNECTION_TIMEOUT=600000
      - ENABLE_DEBUGGER=true