services:
  db:
    image: mysql:8.4.0
    ports:
      - 3306:3306 
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: teste
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    external: true