services:
  postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=botpress
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  botpress:
    image: botpress/server:v12_31_5
    environment:
      - BP_HOST=0.0.0.0
      # - NODE_ENV=production
      - PG_HOST=postgresql
      - PG_PORT=5432
      - PG_USER=teste
      - PG_PASSWORD=teste
      - PG_SSL=false
    ports:
      - 3000:3000

volumes:
  postgresql_data:
    external: true