services:
  php-composer:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - php-composer:/var/www/html
    ports:
      - 8000:8000
    command: tail -f /dev/null
    
volumes:
  php-composer:
    external: true