
services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=Minio@1234
      - MINIO_BROWSER_REDIRECT_URL=http://host.docker.internal:9001
      - MINIO_SERVER_URL=http://host.docker.internal:9000

volumes:
  minio_data:
    external: true