services:
  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - redis_data:/data
    command: redis-server
    # ports:
    #   - 6379:6379

volumes:
  redis_data:
    external: true